"use strict";
const NAVY="#0b2f5b",BLUE="#2f75b5",GOLD="#d6a928",RED="#c00000",GREEN="#2e7d32";
const formatYen=v=>v==null?"—":`¥${Math.round(v).toLocaleString("ja-JP")}`;
const formatThousandYen=v=>v==null?"—":`${Math.round(v/1000).toLocaleString("ja-JP")}千円`;
const formatMillionYen=v=>v==null?"—":`${(v/1e6).toFixed(1)}百万円`;
const formatPercent=v=>v==null?"—":`${(v*100).toFixed(1)}%`;
const monthText=v=>v?`${v.slice(0,4)}年${Number(v.slice(4))}月`:"—";
const fiscalKeys=rows=>[...new Set(rows.flatMap(r=>Object.keys(r).filter(k=>k.endsWith("年度"))))].sort();
function deltaText(v,unit="yen"){if(v==null)return["前年差なし","neutral"];const value=unit==="pt"?`${(Math.abs(v)*100).toFixed(1)}pt`:formatYen(Math.abs(v));return[`${v>=0?"▲":"▼"} 前年差 ${value}`,v>=0?"positive":"negative"]}
function setKpis(k){document.querySelector("#kpi-sales").textContent=formatYen(k.sales);document.querySelector("#kpi-gross").textContent=formatYen(k.gross_profit);document.querySelector("#kpi-margin").textContent=formatPercent(k.gross_margin);document.querySelector("#kpi-achievement").textContent=formatPercent(k.achievement_rate);[["#kpi-sales-yoy",k.sales_yoy,"yen"],["#kpi-gross-yoy",k.gross_profit_yoy,"yen"],["#kpi-margin-yoy",k.gross_margin_yoy,"pt"]].forEach(([id,v,u])=>{const[t,c]=deltaText(v,u);const e=document.querySelector(id);e.textContent=t;e.className=c});const note=document.querySelector("#kpi-achievement-note");note.textContent=k.achievement_rate==null?"計画未登録":"対月次計画";note.className=k.achievement_rate==null?"neutral":k.achievement_rate>=1?"positive":"negative"}
function buildTable(rows,latestMonth){const table=document.querySelector("#comparison-table"),years=fiscalKeys(rows),latest=Number(latestMonth?.slice(4));table.innerHTML=`<caption>年度別 売上・粗利・粗利率比較</caption><thead><tr><th rowspan="2">月</th>${years.map(y=>`<th colspan="3">${y}</th>`).join("")}</tr><tr>${years.map(()=>"<th>売上</th><th>粗利</th><th>粗利率</th>").join("")}</tr></thead><tbody>${rows.map(r=>{const first=r[years[0]]?.gross_margin,last=r[years.at(-1)]?.gross_margin,d=first!=null&&last!=null?last-first:null;return`<tr class="${r.month_number===latest?"latest":""}"><td>${r.month}</td>${years.map((y,i)=>{const v=r[y]||{};const marker=i===years.length-1&&d!=null?`<span class="margin-delta ${d>=0?"positive":"negative"}">${d>=0?"▲":"▼"}${Math.abs(d*100).toFixed(1)}pt</span>`:"";return`<td>${formatMillionYen(v.sales)}</td><td>${formatThousandYen(v.gross_profit)}</td><td>${formatPercent(v.gross_margin)}${marker}</td>`}).join("")}</tr>`}).join("")}</tbody>`;return years}
const dataLabels={id:"dataLabels",afterDatasetsDraw(chart){if(innerWidth<=768)return;const{ctx}=chart;ctx.save();ctx.textAlign="center";ctx.font='bold 10px "Meiryo UI"';chart.data.datasets.forEach((ds,di)=>{const meta=chart.getDatasetMeta(di);meta.data.forEach((el,i)=>{const v=ds.data[i];if(v==null)return;ctx.fillStyle=ds.borderColor||NAVY;const label=ds.type==="line"?formatPercent(v):(v/1e6).toFixed(1);ctx.fillText(label,el.x,el.y+(ds.type==="line"?-9:-6))})});ctx.restore()}};
function fiscalChart(rows,years){const colors=[NAVY,BLUE],sets=[];years.forEach((y,i)=>{sets.push({type:"bar",label:`${y} 売上`,data:rows.map(r=>r[y]?.sales??null),backgroundColor:colors[i],borderRadius:4,barPercentage:.8,categoryPercentage:.75,yAxisID:"sales"});sets.push({type:"line",label:`${y} 粗利率`,data:rows.map(r=>r[y]?.gross_margin??null),borderColor:i?RED:GOLD,backgroundColor:i?RED:GOLD,borderWidth:3,pointRadius:4.5,pointHoverRadius:6,tension:.22,yAxisID:"margin"})});new Chart(document.querySelector("#fiscal-chart"),{data:{labels:rows.map(r=>r.month),datasets:sets},plugins:[dataLabels],options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{position:"bottom",align:"center",labels:{boxWidth:13,font:{size:10}}},tooltip:{callbacks:{title:x=>`${x[0].label}`,label:c=>`${c.dataset.label}：${c.dataset.yAxisID==="margin"?formatPercent(c.raw):formatYen(c.raw)}`}}},scales:{sales:{position:"left",beginAtZero:true,title:{display:true,text:"売上（百万円）"},ticks:{callback:v=>(v/1e6).toFixed(0)},grid:{color:"#e5edf5"}},margin:{position:"right",beginAtZero:true,title:{display:true,text:"粗利率（%）"},ticks:{callback:v=>`${(v*100).toFixed(0)}%`},grid:{drawOnChartArea:false}}}}})}
const splitProduct=(name,rank)=>{const max=17,text=`${rank} ${name}`,parts=[];for(let i=0;i<Math.min(text.length,max*2);i+=max)parts.push(text.slice(i,i+max)+(i+max*2<text.length?"…":""));return parts};
const rankColors=i=>i===0?NAVY:i<3?BLUE:["#74a9d8","#86b5df","#99c1e5","#abcdea","#bcd8ee","#8eb8dc","#6b9fcd"][i-3]||"#9bbfdf";
function rankChart(selector,rows,product=false){const names=rows.map(r=>r.name),labels=rows.map((r,i)=>product?splitProduct(r.name,i+1):`${i+1} ${r.name.length>21?r.name.slice(0,21)+"…":r.name}`);new Chart(document.querySelector(selector),{type:"bar",data:{labels,datasets:[{data:rows.map(r=>r.sales),backgroundColor:rows.map((_,i)=>rankColors(i)),borderRadius:3,barPercentage:.74}]},plugins:[{id:"rankValues",afterDatasetsDraw(c){const{ctx}=c;ctx.save();ctx.fillStyle=NAVY;ctx.font='10px "Meiryo UI"';c.getDatasetMeta(0).data.forEach((b,i)=>ctx.fillText(rows[i].sales>=1e6?formatMillionYen(rows[i].sales):formatThousandYen(rows[i].sales),b.x+5,b.y+3));ctx.restore()}}],options:{indexAxis:"y",responsive:true,maintainAspectRatio:false,layout:{padding:{right:55}},plugins:{legend:{display:false},tooltip:{callbacks:{title:x=>names[x[0].dataIndex],label:c=>`売上：${formatYen(c.raw)}`,afterLabel:c=>{const r=rows[c.dataIndex];return product?[`JAN：${r.jan||"—"}`,`粗利：${formatYen(r.gross_profit)}`,`粗利率：${formatPercent(r.gross_margin)}`,`前年差：${formatYen(r.sales_yoy)}`]:[`粗利：${formatYen(r.gross_profit)}`,`粗利率：${formatPercent(r.gross_margin)}`,`前年差：${formatYen(r.sales_yoy)}`]}}}},scales:{x:{beginAtZero:true,ticks:{callback:v=>v>=1e6?`${(v/1e6).toFixed(1)}百万`:`${Math.round(v/1000)}千`},grid:{color:"#e5edf5"}},y:{grid:{display:false},ticks:{color:"#1f2937",font:{size:10}}}}}})}
function points(data){const k=data.kpi,m=data.manufacturer_top10?.[0],p=data.product_top10?.[0],month=Number(data.meta.latest_month?.slice(4));const prior=k.sales!=null&&k.sales_yoy!=null?k.sales-k.sales_yoy:null,ratio=prior?Math.round(k.sales/prior*1000)/10:null;const items=[...(data.insights||[]),ratio==null?null:`${month}月の売上は前年同月比${ratio}%で${ratio>=100?"前年を上回っています":"前年を下回っています"}。`,k.gross_margin_yoy==null?null:`粗利率は${formatPercent(k.gross_margin)}で前年同月より${Math.abs(k.gross_margin_yoy*100).toFixed(1)}pt${k.gross_margin_yoy>=0?"改善":"悪化"}しました。`,m?`売上トップメーカーは「${m.name}」です。`:null,p?`売上トップ商品は「${p.name}」です。`:null,k.achievement_rate==null?"計画は未登録です。":`計画達成率は${formatPercent(k.achievement_rate)}です。`].filter(Boolean);document.querySelector("#insight-list").innerHTML=[...new Set(items)].map((x,i)=>`<li class="${/下回|悪化/.test(x)?"negative":/改善|上回/.test(x)?"positive":""}">${x}</li>`).join("")}
async function initialize(){const loading=document.querySelector("#loading"),error=document.querySelector("#error-message");try{const r=await fetch("./dashboard_data.json",{cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();document.querySelector("#period").textContent=`${monthText(d.meta.period_start)} ～ ${monthText(d.meta.period_end)}`;document.querySelector("#generated-at").textContent=d.meta.generated_at||"—";setKpis(d.kpi||{});const years=buildTable(d.fiscal_comparison||[],d.meta.latest_month);fiscalChart(d.fiscal_comparison||[],years);rankChart("#manufacturer-chart",d.manufacturer_top10||[],false);rankChart("#product-chart",d.product_top10||[],true);points(d)}catch(e){error.textContent="営業ダッシュボードのデータを読み込めませんでした。update_dashboard.command を実行してデータを更新してください。";console.error(e)}finally{loading.hidden=true}}window.addEventListener("DOMContentLoaded",initialize);
